# Site wide configuration

title: Site Title
locale: en_US
description: Describe your website here.
search: true
share-url: "krakensystems.github.io"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    redcarpet
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-archives

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

mathjax: true



# Octopress

# Default extensions
post_ext: md
page_ext: html

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Kraken
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify: